### ISSUE TITLE
Support `array` type

### ISSUE THREAD

**Issue by jarcand** [openapi/actix-swagger#25]
Unless I'm missing something, the spec supports `array` type but the `parse_schema` function just fails with `unimplemented`:
* https://github.com/openapi/actix-swagger/blob/master/swagg/src/highway/mod.rs#L269

I didn't see any other bug tracking this, so thought I'd start one.

Thanks!

**Comment by sergeysova** [comment]
Hello, thank you for contribution.

can you attach an example swagger file with spec that fails? I going to implement array support

**Comment by jarcand** [comment]
Here's a minimal sample I made:

[openapi-with-array.yaml.txt](https://github.com/openapi/actix-swagger/files/6672679/openapi-with-array.yaml.txt)

Here's the output when compiling:

```
$ RUST_BACKTRACE=1 cargo-swagg openapi-with-array.yaml
thread 'main' panicked at 'not implemented', /home/jarcand/.cargo/registry/src/github.com-1ecc6299db9ec823/swagg-0.3.0/src/highway/mod.rs:269:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/core/src/panicking.rs:50:5
   3: swagg::highway::parse_ref_or_schema
   4: swagg::highway::parse_ref_or_schema
   5: swagg::to_string
   6: cargo_swagg::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sergeysova** [comment]
Thank you. I'm going to review and fix it

**Comment by jayvdb** [comment]
This is a significant blocker for adoption of actix-swagger.
